name: Mive Build

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - 'mive/**'
      - .github/workflow/mive.yaml
  pull_request:
    paths:
      - 'base/**'
      - 'mive/**'
      - .github/workflow/mive.yaml
  workflow_dispatch:
  schedule:
      # 10:37 UTC daily
    - cron: '37 10 * * *'


# Limit this workflow to a single run at a time to avoid race conditions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Images
        run: |
          ./tasks/build-all

      - name: Push Images
        # Push ubuntu base and mive images
        run: docker compose push
